INSERT INTO CAT (id, name, rate, url) VALUES
    (1, 'Amy', 0, 'cats/1.jpg'),
    (2, 'Martin', 0, 'cats/2.jpg'),
    (3, 'Johanna', 0, 'cats/3.jpg'),
    (4, 'Dart', 0, 'cats/4.jpg'),
    (5, 'Nabuchadnezzar', 0, 'cats/5.jpg'),
    (6, 'Ivan', 0, 'cats/6.jpg'),
    (7, 'Tyler', 0, 'cats/7.jpg'),
    (8, 'Jane', 0, 'cats/8.jpg'),
    (9, 'Tom', 0, 'cats/9.jpg'),
    (10, 'Richard', 0, 'cats/10.jpg'),
    (11, 'Cuthbert', 0, 'cats/11.jpg'),
    (12, 'Sir Mullich', 0, 'cats/12.jpg'),
    (13, 'Kate', 0, 'cats/13.jpg'),
    (14, 'Pawz', 0, 'cats/14.jpg');